apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: cos-liberty-build
    creationTimestam: null
  displayName: Customer Order Services on Liberty - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: cos-liberty-dev
    creationTimestam: null
  displayName: Customer Order Services on Liberty - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: cos-liberty-stage
    creationTimestam: null
  displayName: Customer Order Services on Liberty - Stage
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: cos-liberty-prod
    creationTimestam: null
  displayName: Customer Order Services on Liberty - Prod